DROP TABLE IF EXISTS PES_BLOQUEIO;
DROP TABLE IF EXISTS USU_ACESSO;
DROP TABLE IF EXISTS USU_DADOS;
DROP TABLE IF EXISTS FIN_RECEITA;
DROP SEQUENCE IF EXISTS SEQ_CODUSUARIO;

--BANCO DE DADOS FINANCEIRO
CREATE TABLE FIN_RECEITA(
	NUMCPF VARCHAR(11) NOT NULL,
	VALRECEITA NUMERIC(5,2) DEFAULT 0 NOT NULL,
	DATVENCIMENTO DATE NOT NULL,
	FLGPAGO VARCHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_FIN_RECEITA PRIMARY KEY(NUMCPF),
	CONSTRAINT CK_FLGPAGO CHECK (FLGPAGO IN ('N','S'))
)WITH OIDS;

--BANCO DE DADOS AUTENTICAÇÃO
CREATE TABLE USU_DADOS(
	CODUSUARIO NUMERIC(10) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	CONSTRAINT PK_USU_DADOS PRIMARY KEY(CODUSUARIO)
)WITH OIDS;
CREATE SEQUENCE SEQ_CODUSUARIO INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999 NO CYCLE;

CREATE TABLE USU_ACESSO(
	CODUSUARIO NUMERIC(10) NOT NULL,
	ROTA VARCHAR(1000) NOT NULL,
	CONSTRAINT PK_USU_ACESSO PRIMARY KEY(CODUSUARIO, ROTA),
	CONSTRAINT FK_USU_ACESSO_CODUSUARIO FOREIGN KEY (CODUSUARIO) REFERENCES USU_DADOS (CODUSUARIO)
)WITH OIDS;

--BANCO DE DADOS SERASA
CREATE TABLE PES_BLOQUEIO(
	NUMCPF VARCHAR(11) NOT NULL,
	FLGBLOQUEADO VARCHAR(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT PK_PES_BLOQUEIO PRIMARY KEY(NUMCPF),
	CONSTRAINT CK_FLGBLOQUEADO CHECK (FLGBLOQUEADO IN ('N','S'))
)WITH OIDS;

INSERT INTO FIN_RECEITA (NUMCPF,VALRECEITA,DATVENCIMENTO,FLGPAGO) VALUES ('02488731056',570.50,'01/04/2019','S');

INSERT INTO USU_DADOS (CODUSUARIO, EMAIL,SENHA) VALUES ((SELECT NEXTVAL('SEQ_CODUSUARIO')),'gabriel.borchardt@hotmail.com','12345');

INSERT INTO USU_ACESSO (CODUSUARIO,ROTA) VALUES ((SELECT CODUSUARIO FROM USU_DADOS WHERE EMAIL = 'gabriel.borchardt@hotmail.com'),'');

INSERT INTO PES_BLOQUEIO (NUMCPF,FLGBLOQUEADO) VALUES ('02488731056','N');

SELECT * FROM FIN_RECEITA;
SELECT * FROM USU_DADOS;
SELECT * FROM USU_ACESSO;
SELECT * FROM PES_BLOQUEIO;